name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm build-storybook

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false